/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lacoFor;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        for (int i=0; i <=10; i++){ //enquanto i for menor igual a 10 ele irá repetir o numero e somar com 1
	System.out.println (i);
        }
    }
}
