/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lacoSwitch;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        
        /*
        int codigoProduto = 2;

            switch(codigoProduto){
            case 1:
            break; // ponto de parada do bloco
            
            case 2:
            break; //ponto de parada do bloco 

            default: // qualquer outro valor que não seja tratado dentro dos cases.
} */
    }
}
