/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicioPOOn4;

public class App {
    public String getGreeting() {
        return "";
    }
    public static void main(String[] args) {
        InVoice inv = new InVoice(1, "mouse pad", 10, 50.0f);
        System.out.println("Valor total = " + inv.getInVoiceAmount());
    }
}
