/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estruturaCondicionalComLeitor;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
    int numero; //variavel que vai receber o numero

    Scanner leitorScanner = new Scanner(System.in);// função para ler um dado 

    System.out.println("Digite um valor"); // mensagem que irá aparecer antes da leitura do dado
    numero = leitorScanner.nextInt(); // vai pedir para que eu digite um valor comando de entrada de dados

//Estrutura condicional 
        if (numero >= 100 && numero <= 200){
            System.out.println("O número está no intervalo"); // mensagem que irá aparecer caso for verdadeiro
        } else{
            System.out.println("O número não está no intervalo"); // mensagem que irá aparecer caso for falso
        }
    }
}
