/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leituraGravacao;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);

		// entrada de dados
		int idade = leitor.nextInt();
		float cotacaoDolar = leitor.nextFloat();
		double cotacaoEuro = leitor.nextDouble();
		String nome = leitor.nextLine(); // ler uma palavra inteira
		String codigoRua = leitor.next(); // ler uma palavra

		//saida de dados
		System.out.println("Exemplo de saida");
    }
}
