/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estruturaCondicionalIf;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        int media = 7;

            if(media >= 7){ //se verdadeiro
                if(media == 10){ 
            //se verdadeiro 
                    System.out.println("Aprovado com nota máxima");	
                }else{ //se não
                    System.out.println("Aprovado");	
                }
            }else{
            //se não 
                System.out.println("Reprovado");	
            }
    }
}
