/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comentarios;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
     
        // Comentário de uma linha
        
        /*
        Comentário de coluna
        */
        
        /**
         * Comentário de documentação
         */
    }
}
