/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import TodoApp.Controller.ProjectController;
import TodoApp.Model.Project;
import TodoApp.Util.ConnectionFactory;
import java.sql.Connection;
import java.util.List;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        Connection c = ConnectionFactory.getConnection();
        ConnectionFactory.closeConnection(c);   
        
    }
}
